NodeOUs:
    Enable: true
    ClientOUIdentifier:
        Certificate: cacerts/localhost-1020-ca-orderer.pem
        OrganizationalUnitIdentifier: client
    PeerOUIdentifier:
        Certificate: cacerts/localhost-1020-ca-orderer.pem
        OrganizationalUnitIdentifier: peer
    AdminOUIdentifier:
        Certificate: cacerts/localhost-1020-ca-orderer.pem
        OrganizationalUnitIdentifier: admin
    OrdererOUIdentifier:
        Certificate: cacerts/localhost-1020-ca-orderer.pem
        OrganizationalUnitIdentifier: orderer
